### ISSUE TITLE
Running outside GCP

### ISSUE THREAD

**Issue by tadeuszwojcik** [Stackdriver/kubernetes-configs#14]
Hi,
I've found this repo recently as was trying to run Stackdriver outside GCP, in on prem k8s cluster, I've looked into https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/ but it has issues. 
Are configs provided in this repo adjusted so one can run Stackdriver logging/monitoring outside GCP?
Thanks

**Comment by bmoyles0117** [comment]
These configs exist to service the instructions found here: https://cloud.google.com/monitoring/kubernetes-engine/customizing

You're able to set cluster name, location, and credentials to whatever you'd like within the configs, but the agent's default behavior is to determine these values from the GCE Metadata Server when run on GKE using GCP, which is our only supported environment.
