### ISSUE TITLE
Metadata agent fails to authenticate with Google when Workload Identity is enabled

### ISSUE THREAD

**Issue by chribsen** [Stackdriver/kubernetes-configs#41]
After deploying a new cluster with workload identity enabled, the `stackdriver-metadata-agent-cluster-level` pod keeps failing with the following error:

```
Failed to publish resource metadata: rpc error: code = Unauthenticated desc = Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

Given the `Unauthenticated` it clearly seems like the pod doesn't get the proper credentials to the remote service. Can it perhaps be that the stackdriver-metadata-agent still uses [Metadata Concealment](https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata) and doesn't support [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) yet?

## Steps to reproduce

1. Deploy a cluster using the following command:
```
gcloud beta container --project "${PROJECT_ID}" clusters create "${CLUSTER_NAME}" \
 --region "${LOCATION}" \
 --no-enable-basic-auth \
 --cluster-version "1.13.7-gke.8" \
 --machine-type "n1-standard-1" \
 --image-type "COS" \
 --disk-type "pd-ssd" \
 --disk-size "100" \
 --metadata disable-legacy-endpoints=true \
 --service-account "${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com" \
 --num-nodes "1" \
 --enable-stackdriver-kubernetes \
 --enable-ip-alias \
 --network "projects/${PROJECT_ID}/global/networks/default" \
 --subnetwork "projects/${PROJECT_ID}/regions/${LOCATION}/subnetworks/default" \
 --default-max-pods-per-node "110" \
 --enable-network-policy \
 --addons HorizontalPodAutoscaling,HttpLoadBalancing \
 --enable-autoupgrade \
 --enable-autorepair \
 --maintenance-window "22:00" \
 --database-encryption-key "projects/${PROJECT_ID}/locations/${LOCATION}/keyRings/${KEYRING_NAME}/cryptoKeys/${KEY_NAME}" \
 --no-enable-legacy-authorization \
 --identity-namespace "${PROJECT_ID}.svc.id.goog"
```

where
`PROJECT_ID`: Name of the Google project
`CLUSTER_NAME`: Name of your cluster
`LOCATION`: The region to create the cluster in (in our case `europe-west1`)
`SA_NAME`: The Google service account to be used. It must have the following roles; `roles/logging.logWriter, roles/monitoring.metricWriter, roles/monitoring.viewer, roles/cloudkms.cryptoKeyEncrypterDecrypter, roles/stackdriver.resourceMetadata.writer, roles/storage.objectViewer`
`KEYRING_NAME` and `KEY_NAME`: The Cloud KMS keyring and key that should be used to decrypt and encrypt your secrets.

2. Tail the logs for `stackdriver-metadata-agent-cluster-level-*`

```
kubectl -n kube-system logs -f stackdriver-metadata-agent-cluster-level-*
```

**Comment by fproulx-eoscanada** [comment]
I am also seing this. 

Don't know if it's related ^^ , but Workload Identity gives me HTTP 500 and crumbles under normal load that service account keys with secrets would normally chug along....

**Comment by igorpeshansky** [comment]
Thank you for the detailed report. This is a known issue with the Workload Identities EAP integration with Stackdriver. We are working on the fix, but, unfortunately, don't have a workaround other than disabling Workload Identities and using secrets. If you haven't already, you may file a [Cloud Support issue](http://cloud.google.com/support) so you can get notified when a fix is available.

As an aside, the configurations in this repository are not used for GKE. I've updated the repository description to make this clearer.
